### ISSUE TITLE
Few errors running install.sh

### ISSUE THREAD

**Issue by jomivz** [Manyyack/Linux-Set-up#1]
[install-output.txt](https://github.com/Manyyack/Linux-Set-up/files/2970728/install-output.txt)

**Comment by Manyyack** [comment]
Hey jomivz , 
Sorry I missed it. 
This whole repository was created for doing a fresh/clean installation and from your logs I see, you quite has few things set up which I don't think was ideal to delete. 
If you want , please cherry pick the things/configuration you liked. If you have any further issue, please send me e-mail shreel.chhatbar@gmail.com
